$set_environment_variables = <<SCRIPT
tee "/etc/profile.d/myvars.sh" > "/dev/null" <<EOF
export PYGEARS_VERSION=#{ENV['PYGEARS_VERSION']}
EOF
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", inline: $set_environment_variables, run: "always"
  config.vm.provision :shell, path: "../common/build.sh", privileged: false
  config.vm.provision :shell, path: "../common/check_version.sh", privileged: false
  config.vm.provision :shell, path: "../common/test.sh", privileged: false
  config.vm.provision :shell, path: "../common/examples.sh", privileged: false
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
  end
end
