Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/openSUSE-15.0-x86_64"

  config.vm.provision :shell, path: "../common/build_zypper.sh", privileged: false
  config.vm.provision :shell, path: "../common/check_version.sh", privileged: false
  config.vm.provision :shell, path: "../common/test.sh", privileged: false
  config.vm.provision :shell, path: "../common/examples.sh", privileged: false
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
  end
end
